#!/bin/bash

tsdate=$(date +%Y-%m-%d)
tstime=$(date +%H%M%S)
montage /home/pi/photobooth_images/temp_montage.jpg /home/pi/share/WeddingLabel.png -tile 2x1 -geometry +5+5 /home/pi/photobooth_images/montage.jpg
mkdir -p /media/usb/Photos/${tsdate}/montages
cp /home/pi/photobooth_images/montage.jpg /media/usb/Photos/${tsdate}/montages/montage_${tstime}.jpg
lp -d Canon_SELPHY_CP1200 /home/pi/photobooth_images/montage.jpg
rm -f /home/pi/photobooth_images/montage.jpg

