#!/bin/bash

sudo rm -f /home/wtb/montage.jpg
mogrify -resize 968x648 /home/wtb/photobooth_images/*.jpg
montage /home/wtb/photobooth_images/*.jpg -tile 2x2 -geometry +10+10 /home/wtb/photobooth_images/temp_montage.jpg
montage /home/wtb/photobooth_images/temp_montage.jpg /home/wtb/text3336.png -tile 1x2 -geometry +5+5 /home/wtb/montage.jpg
rm -f /home/wtb/photobooth_images/temp_montage.jpg
